### ISSUE TITLE
Expired OAuth details being restored by getStoredCredentials()

### ISSUE THREAD

**Issue by FishOfPrey** [electricimp/Salesforce#13]
I tried to restart my Fridge project after a couple of weeks of inactivity to do some modifications. 
The Agent code started failing with the error message:

> ERROR: [ { "message": "Session expired or invalid", "errorCode": "INVALID_SESSION_ID" } ]

I logged the access_token, and it was indeed expired. From my reading of `getStoredCredentials()` and `getOAuthToken(...)` the oAuth details are persisted as a Squirrel table. This seems problematic, as the access_token expires and needs to be updated using a refresh token periodically. 

I initially tried adding a `server.save({});` immediately after the `server.error` on line [204](https://github.com/electricimp/Salesforce/blob/d1c951860725d4c348fd7aabad312c1576f5542c/examples/SmartRefrigerator/SmartRefrigerator_ExplorerKit_Salesforce.agent.nut#L204). However, that didn't restart to OAuth process to get a valid access_token. 

Seems I also needed to browse to the Agent URL to complete the OAuth steps again.

Failing using the refresh_token, is there a way to clear out the existing expired OAuth details and indicate that the agent URL needs to be browsed to?

**Comment by PadmanPL** [comment]
Have you had your issue solved? I am facing the same problem

**Comment by ppetrosh** [comment]
I am looking into this. I will update the ticket with the results of my investigation and the suggestions.

**Comment by ppetrosh** [comment]
What I found is that refresh token has never been used in the library/examples. So I added update of access token into the smart refrig example. I haven't fully tested it yet, but you should get the idea.

**Comment by ppetrosh** [comment]
fixed in https://github.com/electricimp/Salesforce/releases/tag/v2.0.1
